### PR TITLE
Conversation log merge

### PR DESCRIPTION
**Pull request by alexc19113800**

### CODE REVIEW

**Comment by tg1230** [comment]
Manually merged but how do you display the backlog?

**Comment by alexc19113800** [comment]
> Manually merged but how do you display the backlog?

So essentially you could set ConversationManager's "backlog" variable to a Text. The backlog will be automatically updated whenever a new node is visited.

**Comment by alexc19113800** [comment]
I can write a toggleLog function in ConversationManager and let a button call it.

**Comment by alexc19113800** [comment]
Done, should now be easy to setup a button. Just have it call ConversationManager.ToggleBacklog()

**Comment by tg1230** [comment]
manually merged, all looks good!

**Pull request closed without merging**
